"""tax

Revision ID: 1731a8f9b37a
Revises: 77921b7eec39
Create Date: 2020-08-25 02:22:26.457872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1731a8f9b37a'
down_revision = '77921b7eec39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json_data', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxes')
    # ### end Alembic commands ###
