"""fix

Revision ID: c1fbec22b33f
Revises: 
Create Date: 2020-09-10 17:54:41.782627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fbec22b33f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxes', sa.Column('tip', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxes', 'tip')
    # ### end Alembic commands ###
